#FROM node
#RUN npm install retypeapp --global
#WORKDIR /app
#VOLUME /app
#ENTRYPOINT ["retype"]

FROM retypeapp/retype:latest
#RUN npm install retypeapp --global
WORKDIR /app
VOLUME /app
ENTRYPOINT ["retype"]